jobs:
  test:
    executor: go/default
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          command: |
            wget --quiet https://releases.hashicorp.com/terraform/0.12.23/terraform_0.12.23_linux_amd64.zip
            sudo unzip terraform_0.12.23_linux_amd64.zip -d /usr/local/bin
          name: Install Terraform
      - go/test
  release:
    executor: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install @semantic-release/changelog -D
            - run: npm install @semantic-release/git -D
      - run: npx semantic-release
orbs:
  go: circleci/go@0.2.0
  node: circleci/node@1.1.6
version: 2.1
workflows:
  default:
    jobs:
      - test
      - release:
          filters:
            branches:
              only: master
          requires:
            - test
  version: 2
