jobs:
  lint:
    env:
      AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      AWS_DEFAULT_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.2
      - run: terraform fmt -check -recursive
      - run: terraform init
      - run: terraform validate
name: Format and validate
"on":
  pull_request:
