jobs:
  release:
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: cycjimmy/semantic-release-action@v2.1.3
        with:
          branch: master
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git@8.0.0
name: Create release
"on":
  push:
    branches:
      - master
