jobs:
  test:
    env:
      AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      AWS_DEFAULT_REGION: "${{ secrets.AWS_DEFAULT_REGION }}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.14.2
      - uses: actions/cache@v1
        with:
          key: "${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}"
          path: ~/go/pkg/mod
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.24
          terraform_wrapper: false
      - run: go test -count=1 -timeout=45m ./...
name: Run Terratest
"on":
  pull_request:
